### ISSUE TITLE
How to pass regular expression into CLI?

### ISSUE THREAD

**Issue by csantanapr** [appsody/watcher#7]
I want to use the cli `watcher` to deploy the app when a file changes in my current directory.

I'm unable to see how can I pass a regular expression to the binary.

For example I want to specify a regular expression to watch all my javascript files in my app

Steps to recreate
```
go get github.com/appsody/watcher/cmd/watcher
export APPSODY_WATCH_REGEX="^.*.js$"
watcher \
  --startcmd=false \
  --cmd="./deploy.sh" \
  --ignore="node_modules,app-deploy-remote.yaml" \
  --keepalive=true --dotfiles=false \
  -list \
  ${APPSODY_WATCH_REGEX}
```
I get an error
```
2019/10/18 13:05:03 lstat /Users/csantanapr/dev/kabanero/appsody-app/^.*.js$: no such file or directory
```

**Comment by kylegc** [comment]
Hi Carlos. The APPSODY_WATCH_REGEX is defined by the stack. What stack are you using?

**Comment by csantanapr** [comment]
HI @kylegc I'm using nodejs-express

**Comment by csantanapr** [comment]
Is it possible to pass a glob to the CLI that will make the CLI watch a set of files?

**Comment by kylegc** [comment]
Today the watch files are baked into the stack, so the dev/cli user can't configure it.

For nodejs-express stack, it should be watching all *.js files. See https://github.com/appsody/stacks/blob/master/incubator/nodejs-express/image/Dockerfile-stack#L8

**Comment by csantanapr** [comment]
I want to use the binary standalone, 
I want to watch the files and then run appsody deploy

If the CLI doesn’t this capability to use a regex and you think is not a good feature to have in the watcher binary that’s ok I can close the issue and look for another tool to use

**Comment by kylegc** [comment]
@kewegner what do you think, can the watcher be used as a standalone file watcher outside appsody?

**Comment by kewegner** [comment]
We need to differentiate between watcher and controller.

So in the above example, the line "export APPSODY_WATCH_REGEX="^.*.js$"" will have no effect.

Note,  it is the "controller" not the watcher that has the APPSODY_WATCH_REGEX handling logic.  

As far as the controller.  I am not sure it would work with Windows as it is today.  There would be some work (I think to handle move events) to make it compatible with Windows.

The watcher package itself can work with Windows.  But there may be some limits or set up to do.

Note there is a cli command variation of the watcher we don't use in the controller.
In either case, to use only the watcher package (which is a fork of radofsky), you'd have to follow the radofsky documentation.  Whether you use the command package or watcher.go you would have to do your own coding to use the watcher by itself, as it doesn't have any knowledge of the Appsody environment variables, only the controller does.

Basically to use watcher.go there are several steps:

1) create a new watcher
2) create a handler for the regex
3) Add the recursive directories to watch
4) Start the watcher
5) Set up a polling loop to handle the incoming events.

The runWatcher function of the controller does this.

There also is the cli command line version of the watcher package, and you'd have to see the documentation for that.

Sans possible issues with Windows, it "might" be possible to use the controller as a stand alone file watcher and set the environment variables.  You'd have to take into account all the Appsody Environment variables it needs though.

You could make the "ON_CHANGE" action be the deploy.  I'm not sure what the APPSODY_RUN action is in this example, and whether it would work as is if there was no APPSODY_RUN command without further thought.

**Comment by csantanapr** [comment]
Found a general purpose tool `fswatch` https://github.com/emcrisostomo/fswatch as an alternative

Also updated my guide with an example:
https://ibm-cloud-architecture.github.io/Learning-Kabanero-101/web/1.0.0/appsody-deploy.html#_automate_appsody_deploy
```
fswatch -e .git/ -e app-deploy.yaml -o . | xargs -n1 -I{} "./deploy.sh"
```
